name:                gitlab-webhook
version:             0.1.0.0
license:             BSD3
author:              "Chris Linton-Ford"
copyright:           "2023 Chris Linton-Ford"

extra-source-files:
- README.md
- CHANGELOG.md

description:         "Collect and report spurious CI failures by category"

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- http-client
- modern-uri
- postgresql-simple
- regex-tdfa
- req
- servant
- servant-client
- servant-server
- text
- text-show
- wai
- warp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  gitlab-webhook:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gitlab-webhook

tests:
  gitlab-webhook-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gitlab-webhook
    - hspec
