image: nixos/nix

default:
  tags: 
    - x86_64-linux

spuriobot_nix_build:
  script: "make -C gitlab-webhook build"
  rules:
    - if: $CI_COMMIT_REF_PROTECTED != "true"

spuriobot_nix_build_and_cachix_push:
  script: "make -C gitlab-webhook push"
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
