image: nixos/nix

default:
  tags: 
    - x86_64-linux

spuriobot_nix_build:
  script: ./ci.sh spuriobot_nix_build
  rules:
    - if: $CI_COMMIT_REF_PROTECTED != "true"

spuriobot_nix_build_and_cachix_push:
  script: ./ci.sh spuriobot_nix_build_and_cachix_push
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
