#!/usr/bin/env bash

set -e

outdir="$1"
id="$2"
shift 2

echo $id
url="https://gitlab.haskell.org/ghc/ghc/-/jobs/$id/raw" 
curl --silent -L "$url" | (grep "$@" || echo "") | sed -e "s/^/$id:/" > "$outdir"/"$id"
