#!/usr/bin/env bash

set -e

: ${DB:=jobs.db}

view () {
    echo $1 > current_trace
    curl -L "https://gitlab.haskell.org/ghc/ghc/-/jobs/${1}/raw" | ( LESS=-iRXK less )
}

if [[ $1 -eq "-c" ]]; then
    view "$(xclip -selection clipboard -o)"
elif [[ -n "$@" ]]; then
    for t in "$@"; do
        view $t
    done
else
    sqlite3 "${DB}" "$(xclip -selection clipboard -o)" | while read t; do
        view $t
    done
fi
